name: CommandExtension
main: com.github.nutmegmk0.commandextension.main.ComanndExtension
version: a0.1.0
commands:
  bullet:
    description:
    usage: /<command> player name speed time invisible
    default: op