name: CommandExtension
main: com.github.nutmegmk0.commandextension.main.CommandExtension
version: a0.3.0
commands:
  bullet:
    description:
    usage: /<command> player name speed time invisible
    default: false
    permission: commandextension.basic.bullet
    permission-message: You don't have <permission>
  truedamage:
    description:
    usage: /<command> SearchTargetScorebordTag Damage setNoDamageTime throughNoDamageTick
    default: false
    permission: commandextension.warning.truedamage
    permission-message: You don't have <permission>
  damage:
    description:
    usage: /<command> SearchTargetScorebordTag Damage
    default: op
    permission: commandextension.basic.damage
    permission-message: You don't have <permission>
