name: CommandExtension
main: com.github.nutmegmk0.commandextension.main.CommandExtension
version: a0.2.0
commands:
  bullet:
    description:
    usage: /<command> player name speed time invisible
    default: op
  truedamage:
    description:
    usage: /<command> SearchTargetScorebordTag Damage setNoDamageTime
    default: op